apiVersion: v1
kind: Service
metadata:
  name: frontend-ui
  namespace: default
  labels:
    app: frontend-ui
    app.kubernetes.io/name: frontend-ui
    app.kubernetes.io/component: web-frontend
    app.kubernetes.io/part-of: unified-saas
spec:
  type: ClusterIP
  selector:
    app: frontend-ui
    version: stable
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
