# Default values for universal-app.
replicaCount: 2

image:
  repository: 123456789012.dkr.ecr.me-central-1.amazonaws.com/unified-saas-frontend
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 8080
  name: http

env: []
  # - name: NGINX_PORT
  #   value: "8080"

probes:
  livenessPath: /healthz
  readinessPath: /healthz
  startupPath: /healthz
  port: http

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

networkPolicy:
  enabled: true
  ingressPorts:
    - 8080
  egressPorts:
    - 6432
    - 53
